apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: second-app
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: declarative-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: declarative-app
      tier: backend
  template:
    metadata:
      labels:
        app: declarative-app
        tier: backend
    spec:
      containers:
        - name: second-node
          image: rashmiraj513/kubernetes-first-app:0.1
          resources:
            limits:
              memory: '512Mi'
              cpu: '500m'
            requests:
              memory: '256Mi'
              cpu: '250m'
      restartPolicy: Always
