services:
  mongodb:
    image: 'mongo'
    container_name: mongodb
    volumes:
      - data:/data/db
    # environment:
    # To pass environment variables, there are three options:
    # - MONGO_INITDB_ROOT_USERNAME=max
    # - MONGO_INITDB_ROOT_PASSWORD=secret
    # MONGO_INITDB_ROOT_USERNAME: max
    # MONGO_INITDB_ROOT_PASSWORD: secret
    env_file:
      - ./env/mongo.env

  backend:
    build: ./backend
    container_name: backend_api
    # When the name of Dockerfile is different.
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile
    #   args:
    #     some-arg: 1
    ports:
      - '80:80'
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: frontend_ui
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  data:
  logs:
